# Site settings
title: "Grimoire"
# This is still Saph's baby.  I'm just impatient.
author: "Saph"
description:
  "A searchable D&D 5e spell list, sorted by class and level."
baseurl: "/grimoire" # the subpath of your site, e.g. /blog/
url: "http://detharonil.github.io" # the base hostname & protocol for your site
source-url: "https://github.com/detharonil/grimoire/"
permalink: "/:categories/:title"
exclude: ['LICENSE', 'README.md', '_posts/spell.template']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"
